_target_: diffusion_policy.workspace.train_cfm_unet_hybrid_workspace.TrainCFMUnetHybridWorkspace

taskn:

checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 1
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 4
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: offline
  name: mv_${taskn}
  project: metaworld
  resume: true
  tags:
  - metaworld_${taskn}_image
  - default
multi_run:
  run_dir: data/output/metaworld/${taskn}
  wandb_name_base: metaworld_${taskn}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/output/metaworld/${taskn}
  sweep:
    dir: data/output/metaworld/${taskn}
    subdir: ${hydra.job.num}

n_action_steps: 3
n_latency_steps: 0
n_obs_steps: 2
name: train_cfm_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.cfm_unet_hybrid_image_policy.CFMUnetHybridImagePolicy
  cond_predict_scale: true
  crop_shape:
  - 127
  - 127
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 4
  kernel_size: 5
  n_action_steps: 3
  n_groups: 8
  n_obs_steps: 2
  # noise_scheduler:
  #   _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  #   beta_end: 0.02
  #   beta_schedule: squaredcos_cap_v2
  #   beta_start: 0.0001
  #   clip_sample: true
  #   num_train_timesteps: 100
  #   prediction_type: epsilon
  #   variance_type: fixed_small
  noise_scheduler:
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: 100
      beta_start: 0.0001
      beta_end: 0.02
      beta_schedule: squaredcos_cap_v2
      clip_sample: True
      set_alpha_to_one: True
      steps_offset: 0
      prediction_type: sample

  num_inference_steps: 10
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 4
    obs:
      agent_pos:
        shape:
        - 9
        type: low_dim
      image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
shape_meta:
  action:
    shape:
    - 4
  obs:
    agent_pos:
      shape:
      - 9
      type: low_dim
    image:
      shape:
      - 3
      - 128
      - 128
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.dataset.metaworld_image_dataset.MetaworldImageDataset
    horizon: 4
    max_train_episodes: 90
    pad_after: 2 # {n_action_steps}-1
    pad_before: 1 # {n_obs_steps}-1
    seed: 42
    val_ratio: 0.02
    zarr_path: data/metaworld/metaworld_${taskn}_expert.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.metaworld_image_runner.MetaworldImageRunner
    eval_episodes: 20
    task_name: ${taskn}
    fps: 10
    max_steps: 300
    n_action_steps: 3
    n_envs: null
    n_obs_steps: 2
    n_test: 50
    n_train: 6
    device: ${training.device}

  image_shape:
  - 3
  - 128
  - 128
  name: metaworld_${taskn}_image
  shape_meta:
    action:
      shape:
      - 4
    obs:
      agent_pos:
        shape:
        - 9
        type: low_dim
      image:
        shape:
        - 3
        - 128
        - 128
        type: rgb
task_name: metaworld_${taskn}_image
training:
  checkpoint_every: 200
  debug: False
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 1000
  resume: true
  rollout_every: 200
  sample_every: 100
  seed: ${seed}
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 100
val_dataloader:
  batch_size: 128
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
